title: PLATYPUS NYC EVENTS
description: Platypus NYC Events
author: Platypus Affiliated Society
sidebar_description: The Platypus Affiliated Society, established in December 2006, organizes reading groups, public fora, research and journalism focused on problems and tasks inherited from the “Old” (1920s-30s), “New” (1960s-70s) and post-political (1980s-90s) Left for the possibilities of emancipatory politics today.
avatar: /logo.png
email: coordinator@platypus1917.org
skin: midnight
future: true
timezone: America/New_York

baseurl: "/"
url: "https://platypusnyc.github.io"


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
